[package]
name = "mandelbrot-sandbox"
version = "0.1.0"
authors = ["Zequez <zequez@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.13"
